config/routes.rb
Runners::Application.routes.draw do
  resources :intranets

  resources :relateds

  resources :runners do
   member do
    get :show_lastname #get on specific runner /runners/:id/show_lastname, routed to runners#show_lastname

   end

   collection do
     get :top_three #get on all runners runners/top_three, routed to top_three action of runner controller runners#top_three
    end
  end

  namespace :iadmin do
    resources :posts
    resources :sliders do
      collection { post :sortlist }
    end
    resources :slides

  end
  resources :categories
  get '/:year/:month/:day/:slug' => 'posts#show', :constraints => {:year => /(20)\d{2}/, :month => /\d{2}/, :day => /\d{2}/}, :as => :permalink
  root :to => 'runners#index'
  get 'blog' => 'posts#index'
  get 'slider' => 'sliders#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new' ,            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match "/sliders/:id" => "sliders#show",       via: 'get'

  

end

app/models/intranet.rb
class Intranet < ActiveRecord::Base

	attr_writer :start_time_text #set to an @instance variable (@start_time_text)

	validates_presence_of :start_time_text
	validate :check_start_time_text
	before_save :save_start_time_text

def start_time_text
	@start_time_text || start_time.try(:strftime, "%Y-%m-%d %H:%M:%S")
end


def save_start_time_text
	self.start_time = Time.zone.parse(@start_time_text) if @start_time_text.present?
end

def check_start_time_text
	if @start_time_text.present? && Time.zone.parse(@start_time_text).nil?
		errors.add :start_time_text, "Cannot accept date"
	end
	rescue ArgumentError
	errors.add :start_time_text, "Argument error"
end

end

app/controllers/intranets_controller.rb
class IntranetsController < ApplicationController
  before_action :set_intranet, only: [:show, :edit, :update, :destroy]

  # GET /intranets
  # GET /intranets.json
  def index
    @intranets = Intranet.all
  end

  # GET /intranets/1
  # GET /intranets/1.json
  def show
  end

  # GET /intranets/new
  def new
    @intranet = Intranet.new
  end

  # GET /intranets/1/edit
  def edit
  end

  # POST /intranets
  # POST /intranets.json
  def create
    @intranet = Intranet.new(intranet_params)

    respond_to do |format|
      if @intranet.save
        format.html { redirect_to @intranet, notice: 'Intranet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @intranet }
      else
        format.html { render action: 'new' }
        format.json { render json: @intranet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /intranets/1
  # PATCH/PUT /intranets/1.json
  def update
    respond_to do |format|
      if @intranet.update(intranet_params)
        format.html { redirect_to @intranet, notice: 'Intranet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @intranet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /intranets/1
  # DELETE /intranets/1.json
  def destroy
    @intranet.destroy
    respond_to do |format|
      format.html { redirect_to intranets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intranet
      @intranet = Intranet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def intranet_params
      params.require(:intranet).permit(:category_name, :show, :start_time, :start_time_text, :finish_time)
    end
end

app/helpers/intranets_helper.rb
module IntranetsHelper
end

app/views/intranets/_form.html.erb
<%= form_for(@intranet) do |f| %>
  <% if @intranet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@intranet.errors.count, "error") %> prohibited this intranet from being saved:</h2>

      <ul>
      <% @intranet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_name %><br>
    <%= f.text_area :category_name %>
  </div>
  <div class="field">
    <%= f.label :show %><br>
    <%= f.check_box :show %>
  </div>

   <div class="field">
    <%= f.label :start_time_text %><br>
    <%= f.text_field :start_time_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/intranets/edit.html.erb
<h1>Editing intranet</h1>

<%= render 'form' %>

<%= link_to 'Show', @intranet %> |
<%= link_to 'Back', intranets_path %>

app/views/intranets/index.html.erb
<h1>Listing intranets</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th>Show</th>
      <th>Start</th>
      <th>Finish</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @intranets.each do |intranet| %>

      <tr>
        <td><%= intranet.category_name %></td>
        <td><% if intranet.show == true %><%= intranet.show  %><% else %><strong><%= intranet.show  %></strong><% end %></td>
        <td><% if intranet.start_time.present? %><%= intranet.start_time.strftime("Starts on %d %B at %H:%M%p") %><% end %></td>
        <td><%= intranet.finish_time.to_s %></td>
        <td><%= link_to 'Show', intranet %></td>
        <td><%= link_to 'Edit', edit_intranet_path(intranet) %></td>
        <td><%= link_to 'Destroy', intranet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intranet', new_intranet_path %>

app/views/intranets/new.html.erb
<h1>New intranet</h1>

<%= render 'form' %>

<%= link_to 'Back', intranets_path %>

app/views/intranets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @intranet.category_name %>
</p>

<p>
  <strong>Show:</strong>
  <%= @intranet.show %>
</p>

<%= link_to 'Edit', edit_intranet_path(@intranet) %> |
<%= link_to 'Back', intranets_path %>