config/routes.rb
Runners::Application.routes.draw do
  resources :intranets

  resources :relateds

  resources :runners do
   member do
    get :show_lastname #get on specific runner /runners/:id/show_lastname, routed to runners#show_lastname

   end

   collection do
     get :top_three #get on all runners runners/top_three, routed to top_three action of runner controller runners#top_three
    end
  end

  namespace :iadmin do
    resources :posts
    resources :sliders do
      collection { post :sortlist }
    end
    resources :slides

  end
  resources :categories
  get '/:year/:month/:day/:slug' => 'posts#show', :constraints => {:year => /(20)\d{2}/, :month => /\d{2}/, :day => /\d{2}/}, :as => :permalink
  root :to => 'runners#index'
  get 'blog' => 'posts#index'
  get 'slider' => 'sliders#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new' ,            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match "/sliders/:id" => "sliders#show",       via: 'get'

  

end

app/models/runner.rb
class Runner < ActiveRecord::Base

has_and_belongs_to_many :shoes
accepts_nested_attributes_for :shoes

	validates :firstname, presence: true
  
  include Name #testing concerns

end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:show_lastname, :show, :edit, :update, :destroy]

  # GET /runners
  # GET /runners.json
  def index #mapped as a GET request to the index.html.erb file
    @runners = Runner.all 

  end

  # GET /runners/1
  # GET /runners/1.json
  def show
   
    
  end


  def top_three
    @runners = Runner.order(created_at: :desc).take(3)
    @runner_count = @runners.count
  end

 # GET /runners/1/show_lastname
  def show_lastname
  end


  # GET /runners/new
  def new
    @runner = Runner.new #make avaialable to the view @runner instance variable
    @runner.shoes.build #build method returns a new object of the associated type ready to be filled and saved    

  end

  # GET /runners/1/edit
  def edit 
    if @runner.shoes.empty? #if no associated record exists ensure a form field shows by calling the build method
      @runner.shoes.build #build method returns a new object of the associated type ready to be filled and saved
    end
  end

  # POST /runners
  # POST /runners.json
  def create
    @runner = Runner.new(runner_params)

    respond_to do |format|
      # Rails can automatically respond differently to different client request.  If a client i.e browser wants HTML rails responds with HTML.
      if @runner.save                    
       # If the validations pass and the runner gets saved redirect to the show page of the new record, otherwise refresh/render the new page (hopefully showing what error caused the record to fail to save).

        format.html { redirect_to @runner, notice: 'Runner was successfully created.' } 
        # Call redirect_to to send an HTTP redirect status code to the browser
        format.json { render action: 'show', status: :created, location: @runner }
      else
         # render creates a full response to send back to the browser
        format.html { render action: 'new' } #server sends information back to the client browser uses the action new (which show the new view)
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runners/1
  # PATCH/PUT /runners/1.json
  def update
    respond_to do |format|
      if @runner.update(runner_params) #dont need to call new as object already exists
        format.html { redirect_to @runner, notice: 'Runner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @runner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runners/1
  # DELETE /runners/1.json
  def destroy
    @runner.destroy
     # destroy is a more thourough delete and will check the options of this records associations and destroy the associated objects as well if they are dependant on this object. 

    respond_to do |format|
      format.html { redirect_to runners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.find(params[:id]) #find is a method of activecontroller 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def runner_params
        params.require(:runner).permit(:id, :firstname, :lastname, :age, :gender, shoes_attributes: [:id, :runner_id, :shoe_id, :size, :make, :shoe_type] )#address_attributes: [:runner_id, :city], runners_shoes_attributes: [:runner_id, :shoe_id])
    end
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_form.html.erb
<%= form_for(@runner) do |f| %>
  <% if @runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% @runner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname, 'First Name' %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname, 'Last Name' %><br>
    <%= f.text_field :lastname %>
  </div>

  <%= f.fields_for :shoes, @runner.shoes do |shoe_fields| %>
   <div class="field">
    <%= f.label :size, 'Shoe Size' %><br>
    <%= shoe_fields.text_field :size %>
</div>
    <div class="field">
    <%= f.label :shoe_type, 'Shoe Type' %><br>
    <%= shoe_fields.text_field :shoe_type %>
</div>
    <div class="field">
    <%= f.label :make, 'Shoe Make'%><br>
    <%= shoe_fields.text_field :make %>
    </div>
<% end %>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runners/edit.html.erb
<h1>Editing runner</h1>

<%= render 'form' %>

<%= link_to 'Show', @runner %> |
<%= link_to 'Back', runners_path %>
<%= link_to 'Destroy', @runner, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/runners/index.html.erb
<h1>Listing runners</h1>
<div id="sidebar">A navigation here</div>
<div id ="main">
<table id="runners-table">
  <thead>
    <tr>
      <th>Fullname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @runners.each do |runner| %>
      <tr>
        <td><%= runner.fullname %></td>
        <td><%= link_to 'Show', runner %></td>
        <td><%= link_to 'Edit', edit_runner_path(runner) %></td>
        <td><%= link_to 'Destroy', runner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Runner', new_runner_path %>
</div>

app/views/runners/new.html.erb
<h1>New runner</h1>

<%= render 'form' %>

<%= link_to 'Back', runners_path %>

app/views/runners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Runner Full Name:</strong>
  <%= @runner.fullname %>
</p>

 <% @runner.shoes.each do |shoe_fields| %>
<%= shoe_fields.size %>
<%= shoe_fields.make %>
<%= shoe_fields.shoe_type %>
<% end %>
<%= link_to 'Edit', edit_runner_path(@runner) %> |
<%= link_to 'Back', runners_path %>

app/views/runners/show_lastname.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @runner.lastname %>
</p>

app/views/runners/top_three.html.erb
<h1>Listing last 
  <%= @runner_count %> runners</h1>
<div id="sidebar">A navigation here</div>
<div id ="main">
<table id="runners-table">
  <thead>
    <tr>
      <th>Fullname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @runners.each do |runner| %>
      <tr>
        <td><%= runner.fullname %></td>
        <td><%= link_to 'Show', runner %></td>
        <td><%= link_to 'Edit', edit_runner_path(runner) %></td>
        <td><%= link_to 'Destroy', runner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Runner', new_runner_path %>
</div>