config/routes.rb
Runners::Application.routes.draw do
  resources :intranets

  resources :relateds

  resources :runners do
   member do
    get :show_lastname #get on specific runner /runners/:id/show_lastname, routed to runners#show_lastname

   end

   collection do
     get :top_three #get on all runners runners/top_three, routed to top_three action of runner controller runners#top_three
    end
  end

  namespace :iadmin do
    resources :posts
    resources :sliders do
      collection { post :sortlist }
    end
    resources :slides

  end
  resources :categories
  get '/:year/:month/:day/:slug' => 'posts#show', :constraints => {:year => /(20)\d{2}/, :month => /\d{2}/, :day => /\d{2}/}, :as => :permalink
  root :to => 'runners#index'
  get 'blog' => 'posts#index'
  get 'slider' => 'sliders#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new' ,            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match "/sliders/:id" => "sliders#show",       via: 'get'

  

end

app/models/slider.rb
class Slider < ActiveRecord::Base
  has_many :slides, -> { order("slides.sort ASC") }, :dependent => :destroy
  accepts_nested_attributes_for :slides, :reject_if => lambda { |a| a[:description].blank? }, :allow_destroy => true
end

app/controllers/iadmin/posts_controller.rb
class Iadmin::PostsController < ApplicationController
	before_action :set_post, only: [:show_lastname, :edit, :update, :destroy]

  def index #mapped as a GET request to the index.html.erb file
    @posts = Post.order('publish_date DESC')
    @categories = Category.all
    @posts = @posts.by_category_id(params[:category]) if params[:category].present?
  end

  # def show
  #    @post = Post.find_by_slug(params[:slug])
  # end

  def new
  	@post = Post.new
  end

  def edit
  	if @post.categories.empty? #if no associated record exists ensure a form field shows by calling the build method
    end
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save                    
        format.html { redirect_to iadmin_posts_path, notice: 'Runner was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    params[:post][:category_ids] ||= []
    respond_to do |format|
      if @post.update(post_params) 
        format.html { redirect_to iadmin_posts_path, notice: 'post was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to iadmin_posts_path }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id]) #find is a method of activecontroller 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
        params.require(:post).permit(:id, :title, :excerpt, :body, :slug, :publish_date, :category_ids => [], categories_attributes: [:id, :name] )
    end
end

app/controllers/iadmin/sliders_controller.rb
class Iadmin::SlidersController < ApplicationController
	before_action :set_slider, only: [:edit, :sortable, :update, :destroy]

  def index #mapped as a GET request to the index.html.erb file
    @sliders = Slider.all
    @slider = Slide.all
    # @sliders = @sliders.by_slide_id(params[:slide]) if params[:slide].present?
  end

  # def show
  #    @slider = slider.find_by_slug(params[:slug])
  # end

  def new
  	@slider = Slider.new
    1.times do
      slide = @slider.slides.build
    end
  end

  def edit
  	if @slider.slides.empty? #if no associated record exists ensure a form field shows by calling the build method
    end
   
  end

  def create
    @slider = Slider.new(slider_params)

    respond_to do |format|
      if @slider.save                    

        format.html { redirect_to iadmin_sliders_path, notice: 'Slider was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    params[:slider][:slide_ids] ||= []
    respond_to do |format|
      if @slider.update(slider_params) 
        format.html { redirect_to iadmin_sliders_path, notice: 'Slider was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end


  def destroy
    @slider = Slider.find(params[:id])
    @slider.destroy

    respond_to do |format|
      format.html { redirect_to iadmin_sliders_path }
      format.json { head :no_content }
    end
  end

  def sortlist


    params[:slide].each_with_index do |id, index|
     Slide.update_all({sort: index+1}, {id: id})
  end
  render nothing: true
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider
      @slider = Slider.find(params[:id]) #find is a method of activecontroller 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slider_params
        params.require(:slider).permit(:id, :title, slides_attributes: [:id, :description, :image, :image_slide, :slide_image_file_name, :sorted, :_destroy ] )
    end

end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  before_action :set_slider, only: :show 

  # def index #mapped as a GET request to the index.html.erb file
  #   @sliders = Slider.all
  #   @slides = Slide.all
  #   @sliders = @sliders.by_slide_id(params[:slide]) if params[:slide].present?
  # end

   def show
    @slider = Slider.find(params[:id]) 
   end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slider
      @slider = Slider.find(params[:id]) #find is a method of activecontroller 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slider_params
        params.require(:slider).permit(:id, :title, slides_attributes: [:id, :description, :image, :image_slide, :slide_image_file_name, :_destroy ] )
    end

end

app/views/iadmin/sliders/_form.html.erb
<%= form_for [:iadmin, @slider], :url =>  [:iadmin, @slider], :html => { :multipart => true } do |f| %>
  <% if @slider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slider.errors.count, "error") %> prohibited this slider from being saved:</h2>
      <ul>
       <% @slider.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Title' %><br>
    <%= f.text_field :title %>
  </div> 

  <ul id="sortable" data-update-url="<%= sortlist_iadmin_sliders_url %>" >
    <%= f.fields_for :slides do |builder| %>
    <%= render 'slide_fields', f: builder %>
    <% end %>
    <%= link_to_add_fields "Add Slide", f, :slides %>
  </ul> 

  <hr>

  

  <div class="form-actions">
    <%= f.submit 'Save', :class =>'btn btn-primary' %>
    <%= link_to 'Cancel', iadmin_sliders_path, :class=> "btn" %>
  </div>
<% end %>

app/views/iadmin/sliders/_slide_fields.html.erb
<%= content_tag_for :li, f.object do %>
  <span class="handle">[Drag]</span>
  <%= f.label :description, 'Description' %><br />
  <%= f.text_field :description %>
  <%= f.label :image_slide, 'Slide Image' %><br />
  <%= f.file_field :image_slide %>
  <%= image_tag f.object.image_slide.url(:medium) if f.object.image_slide %>
  <%= f.hidden_field :_destroy, :class => 'hidden' %><br />
  <button type="button" class="btn btn-default"><%= link_to "Remove", "#", :class => 'remove_fields' %></button>
<% end %>

app/views/iadmin/sliders/edit.html.erb
<h1>Editing slider</h1>

<%= render 'form' %>

app/views/iadmin/sliders/index.html.erb
<h1>Listing Sliders</h1>
<%= link_to 'New Slider', new_iadmin_slider_path %>
<table class="table table-striped">
<thead>
<tr>
<th>Title</th>
<th>Code to add slider</th>
<th>Slide</th>
<th></th>
</tr>
</thead>
<tbody>
<% @sliders.each do |slider| %>
<tr>
<td>
<%= link_to slider.title, edit_iadmin_slider_path(slider) %>
</td>
<td>
 <%= raw "<%= display_slider('#{slider.id}') %" %><%= raw ">" %>
</td>
<td>
<table>
<tbody>
<% slider.slides.each do |slide| %>
<!--  <%= content_tag_for :li, slide do %> -->
 <tr><td>
<%= slide.description %></td>
<td>
<%= image_tag slide.image_slide.url(:small) %>
</td>
</tr>
<% end %>
<% end %>
</tbody>
</table>
</td>
<td><%= link_to 'View', iadmin_slider_path(slider)%> <%= link_to 'Destroy', iadmin_slider_path(slider), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/iadmin/sliders/new.html.erb
<h1>New Slider</h1>

<%= render 'form' %>