config/routes.rb
Runners::Application.routes.draw do
  resources :intranets

  resources :relateds

  resources :runners do
   member do
    get :show_lastname #get on specific runner /runners/:id/show_lastname, routed to runners#show_lastname

   end

   collection do
     get :top_three #get on all runners runners/top_three, routed to top_three action of runner controller runners#top_three
    end
  end

  namespace :iadmin do
    resources :posts
    resources :sliders do
      collection { post :sortlist }
    end
    resources :slides

  end
  resources :categories
  get '/:year/:month/:day/:slug' => 'posts#show', :constraints => {:year => /(20)\d{2}/, :month => /\d{2}/, :day => /\d{2}/}, :as => :permalink
  root :to => 'runners#index'
  get 'blog' => 'posts#index'
  get 'slider' => 'sliders#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new' ,            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match "/sliders/:id" => "sliders#show",       via: 'get'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
	# has_and_belongs_to_many :posts
		# has_many :categories_posts
	 #    has_many :posts, through: :categories_posts
	 has_and_belongs_to_many :posts
	 validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show_lastname, :show, :edit, :update, :destroy]

  def index #mapped as a GET request to the index.html.erb file
    @categories = Category.all 
  end

  def new
  	@category = Category.new
  	# @category.categories.build
  end

  def show
  end

  def edit
  	# if @category.categories.empty? #if no associated record exists ensure a form field shows by calling the build method
      # @category.categories.build #build method returns a new object of the associated type ready to be filled and saved
    # end
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save                    

        format.html { redirect_to @category, notice: 'Runner was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params) 
        format.html { redirect_to @category, notice: 'category was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id]) #find is a method of activecontroller 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
        params.require(:category).permit(:id, :name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Category Name' %><br>
    <%= f.text_field :name %>
  </div> 


  <div class="form-actions">
     <%= f.submit 'Save', :class =>'btn btn-primary' %>
  <%= link_to 'Cancel', categories_path, :class=> "btn" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= link_to category.name, edit_category_path(category) %></td>
        <td><button type="button" class="btn btn-danger"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br />
<button type="button" class="btn btn-primary"><%= link_to 'New category', new_category_path %></button>

app/views/categories/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @category.name %></h1>
<p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>